name: quality_link_client
description: Der offizielle Client f체r QualityLink Services.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # System
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  device_info_plus: ^11.1.0
  timeago: ^3.6.1
  
  # Netzwerk
  http: ^1.2.0
  network_info_plus: ^5.0.0
  
  # Dateien
  file_picker: ^8.0.0+1
  archive: ^3.6.1
  path: ^1.9.0
  url_launcher: ^6.3.1

  # Background Service (NEU)
  flutter_foreground_task: ^8.17.0  # F체r Android Background
  flutter_overlay_window: ^0.5.0 # Dynamische Overlays
  flutter_local_notifications: ^17.0.0
  
  # UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  
  # Video (f체r FFmpeg sp채ter)
  video_player: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true